version: "3.7"

x-services-volume:
  &services-volume
  type: bind
  source: ./app
  target: /app

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      shm_size: "20g"
    shm_size: "20g"
    ports:
      - 8003:8003
    restart: always
    volumes:
      - *services-volume
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    command: >
      sh -c "uvicorn core.fast_api_endpoints:app --host 0.0.0.0 --port 8003 --reload"
    depends_on:
      - redis

  broker:
    hostname: broker
    container_name: broker
    image: rabbitmq:3
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  celery_worker:
    hostname: celery_worker
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
      shm_size: "4g"
    shm_size: "4g"
    command: celery -A core.celery_worker.celery worker --loglevel=info
    volumes:
      - *services-volume
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    depends_on:
      - app
      - broker
      - redis

  redis:
    hostname: redis
    container_name: redis
    image: redislabs/rejson:2.4.3
    ports:
      - 6379:6379