version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      shm_size: "1g"
    shm_size: "2g"
    ports:
      - 8003:8003
    restart: always
    volumes:
      - ./app:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    command: >
      sh -c "uvicorn core.fast_api_automation:app --host 0.0.0.0 --port 8003 --reload"

  broker:
    hostname: broker
    container_name: broker
    image: rabbitmq:3
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  celery_worker:
    hostname: celery_worker
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
      shm_size: "1g"
    shm_size: "2g"
    command: celery -A core.celery_worker.celery worker --loglevel=info
    volumes:
      - ./app:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    depends_on:
      - app
      - broker
